version: '2'

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cocktailize

  server:
    build: .
    image: loick111/cocktailize
    ports:
      - "8080:8080"
    links:
      - db